# Generated by Django 4.1 on 2023-02-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("content_length", models.IntegerField(default=100)),
                ("category", models.CharField(max_length=70)),
                ("project", models.CharField(max_length=70)),
                ("spider", models.CharField(max_length=70)),
                ("server", models.CharField(max_length=70)),
                ("date_scraped", models.DateField()),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default="False",
                        max_length=5,
                    ),
                ),
                (
                    "short",
                    models.CharField(
                        choices=[("True", "True"), ("False", "False")],
                        default="False",
                        max_length=5,
                    ),
                ),
                ("link_no", models.IntegerField()),
                ("no", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "Questions",
            },
        ),
    ]
