# Generated by Django 4.1 on 2023-02-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="questions",
            table="questions",
        ),
    ]
